TCC-WEB/src/java/Bean/CrudBean.java
package Bean;

import DAO.InterfaceCrudDAO;
import Controle.ErroSistema;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

public abstract class CrudBean<E, D extends InterfaceCrudDAO> {
    
    private String estadoTela = "buscar";
    private E entidade;
    private List<E> entidades;
    
    public CrudBean() {
        entidade = criarNovaEntidade();
    }
    
    public void newEnt() {
        entidade = criarNovaEntidade();
        mudarParaInseri();
    }
    
    public void clear() {
        entidade = criarNovaEntidade();
    }
    
    public void returnPes() {
        clear();
        mudarParaBusca();
    }
    
    public void save() {
        try {
            getDAO().salvar(entidade);
            entidade = criarNovaEntidade();
            adicionarMensagem("Salvo com sucesso!", FacesMessage.SEVERITY_INFO);
            mudarParaBusca();
        } catch (ErroSistema ex) {
            Logger.getLogger(CrudBean.class.getName()).log(Level.SEVERE, null, ex);
            adicionarMensagem(ex.getMessage(), FacesMessage.SEVERITY_ERROR);
        }
    }
    
    public void change(E entidade) {
        this.entidade = entidade;
        mudarParaEdita();
    }
    
    public void delete(E entidade) {
        try {
            getDAO().deletar(entidade);
            entidades.remove(entidade);
            adicionarMensagem("Deletado com sucesso!", FacesMessage.SEVERITY_INFO);
        } catch (ErroSistema ex) {
            Logger.getLogger(CrudBean.class.getName()).log(Level.SEVERE, null, ex);
            adicionarMensagem(ex.getMessage(), FacesMessage.SEVERITY_ERROR);
        }
    }
    
    public void search() {
        if (!isBusca()) {
            mudarParaBusca();
            return;
        }
        try {
            entidades = getDAO().buscar(entidade);
            if (entidades == null || entidades.size() < 1) {
                adicionarMensagem("Não existe nada cadastrado!", FacesMessage.SEVERITY_WARN);
            }
        } catch (ErroSistema ex) {
            Logger.getLogger(CrudBean.class.getName()).log(Level.SEVERE, null, ex);
            adicionarMensagem(ex.getMessage(), FacesMessage.SEVERITY_ERROR);
        }
        
    }
    
    public void adicionarMensagem(String mensagem, FacesMessage.Severity tipoErro) {
        FacesMessage fm = new FacesMessage(tipoErro, mensagem, null);
        FacesContext.getCurrentInstance().addMessage(null, fm);
    }
    
    public E getEntidade() {
        return entidade;
    }

    public void setEntidade(E entidade) {
        this.entidade = entidade;
    }

    public List<E> getEntidades() {
        return entidades;
    }

    public void setEntidades(List<E> entidades) {
        this.entidades = entidades;
    }
    
    public abstract D getDAO();
    
    public abstract E criarNovaEntidade();
    
    public boolean isInseri() {
        return "inserir".equals(estadoTela);
    }
    
    public boolean isEdita() {
        return "editar".equals(estadoTela);
    }
    
    public boolean isBusca() {
        boolean bc = "buscar".equals(estadoTela);
        return bc;
    }
    
    public void mudarParaInseri() {
        estadoTela = "inserir";
    }
    
    public void mudarParaEdita() {
        estadoTela = "editar";
    }
    
    public void mudarParaBusca() {
        estadoTela = "buscar";
    }
}

TCC-WEB/src/java/Bean/FinanceiroBean.java
package Bean;

import Entidades.Financeiro;
import DAO.FinanceiroDAO;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class FinanceiroBean extends CrudBean<Financeiro, FinanceiroDAO>{

    private FinanceiroDAO finDAO;
    
    @Override
    public FinanceiroDAO getDAO() {
        if (finDAO == null) {
            finDAO = new FinanceiroDAO();
        }
        return finDAO;
    }

    @Override
    public Financeiro criarNovaEntidade() {
        return new Financeiro();
    }
    
}

TCC-WEB/src/java/Bean/GranjaCorteBean.java
package Bean;

import Entidades.GranjaCorte;
import DAO.GranjaCorteDAO;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class GranjaCorteBean extends CrudBean<GranjaCorte, GranjaCorteDAO>{

    private GranjaCorteDAO gcDAO;
    
    @Override
    public GranjaCorteDAO getDAO() {
        if (gcDAO == null) {
            gcDAO = new GranjaCorteDAO();
        }
        return gcDAO;
    }

    @Override
    public GranjaCorte criarNovaEntidade() {
        return new GranjaCorte();
    }
    
}

TCC-WEB/src/java/Bean/GranjaOvosBean.java
package Bean;

import Entidades.GranjaOvos;
import DAO.GranjaOvosDAO;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class GranjaOvosBean extends CrudBean<GranjaOvos, GranjaOvosDAO>{

    private GranjaOvosDAO goDAO;
    
    @Override
    public GranjaOvosDAO getDAO() {
        if (goDAO == null) {
            goDAO = new GranjaOvosDAO();
        }
        return goDAO;
    }

    @Override
    public GranjaOvos criarNovaEntidade() {
        return new GranjaOvos();
    }
}

TCC-WEB/src/java/Bean/IncubatorioBean.java
package Bean;

import Entidades.Incubatorio;
import DAO.IncubatorioDAO;
import Controle.ErroSistema;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class IncubatorioBean extends CrudBean<Incubatorio, IncubatorioDAO>{

    private IncubatorioDAO incDAO;
    
    @Override
    public IncubatorioDAO getDAO() {
        if (incDAO == null) {
            incDAO = new IncubatorioDAO();
        }
        return incDAO;
    }

    @Override
    public Incubatorio criarNovaEntidade() {
        return new Incubatorio();
    }
}

TCC-WEB/src/java/Bean/OvosBean.java
package Bean;

import Entidades.Ovos;
import DAO.OvosDAO;
import Controle.ErroSistema;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class OvosBean extends CrudBean<Ovos, OvosDAO> {

    private OvosDAO ovDAO;

    @Override
    public OvosDAO getDAO() {
        if (ovDAO == null) {
            ovDAO = new OvosDAO();
        }
        return ovDAO;
    }

    @Override
    public Ovos criarNovaEntidade() {
        return new Ovos();
    }
    
    public List<String> buscaListaString() {
        try {
            return getDAO().buscarListaLote();
        } catch (ErroSistema ex) {
            Logger.getLogger(OvosBean.class.getName()).log(Level.SEVERE, null, ex);
            adicionarMensagem(ex.getMessage(), FacesMessage.SEVERITY_ERROR);
        }
        return null;
    }
}

TCC-WEB/src/java/Bean/RacaoBean.java
package Bean;

import Entidades.Racao;
import DAO.RacaoDAO;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class RacaoBean extends CrudBean<Racao, RacaoDAO>{

    private RacaoDAO raDAO;
    
    @Override
    public RacaoDAO getDAO() {
        if (raDAO == null) {
            raDAO = new RacaoDAO();
        }
        return raDAO;
    }

    @Override
    public Racao criarNovaEntidade() {
        return new Racao();
    }  
}

TCC-WEB/src/java/Bean/TipoRacaoBean.java
package Bean;

public class TipoRacaoBean {
    
}

TCC-WEB/src/java/Bean/UsuarioBean.java
package Bean;

import Entidades.Usuario;
import Bean.CrudBean;
import DAO.UsuarioDAO;
import Controle.ErroSistema;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class UsuarioBean extends CrudBean<Usuario, UsuarioDAO>{

    private UsuarioDAO usuDAO;
    
    @Override
    public UsuarioDAO getDAO() {
        if (usuDAO == null) {
            usuDAO = new UsuarioDAO();
        }
        return usuDAO;
    }

    @Override
    public Usuario criarNovaEntidade() {
        return new Usuario();
    }
}

TCC-WEB/src/java/Bean/VacinaBean.java
package Bean;

import Entidades.Vacina;
import Bean.CrudBean;
import DAO.VacinaDAO;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@SessionScoped
@ManagedBean
public class VacinaBean extends CrudBean<Vacina, VacinaDAO>{

    private VacinaDAO vacDAO;
    
    @Override
    public VacinaDAO getDAO() {
        if (vacDAO == null) {
            vacDAO = new VacinaDAO();
        }
        return vacDAO;
    }

    @Override
    public Vacina criarNovaEntidade() {
        return new Vacina();
    } 
}

TCC-WEB/web/botoesPadroes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:decorate xmlns="http://www.w3.org/1999/xhtml"
             xmlns:h="http://xmlns.jcp.org/jsf/html"
             xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
             xmlns:p="http://primefaces.org/ui">
    
    <h:form>
        <p:commandButton value="Pesquisar" update="@form" action=""></p:commandButton>
        <p:commandButton value="Voltar" update="@form" action=""></p:commandButton>
        <p:commandButton value="Adicionar" update="@form" action=""></p:commandButton>
        <p:commandButton value="Salvar" update="@form" action=""></p:commandButton>
        <p:commandButton value="Limpar" update="@form" action=""></p:commandButton>
    </h:form>
</ui:decorate>>

TCC-WEB/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:decorate xmlns="http://www.w3.org/1999/xhtml"
             xmlns:h="http://xmlns.jcp.org/jsf/html"
             xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
             template="menu.xhtml"
             xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Home</title>
    </h:head>
    <h:form>
        
    </h:form>

</ui:decorate>

TCC-WEB/web/menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:body>
        <h:form>
            <p:menubar style="background: #eee">
                <p:menuitem value="Inicio" url="index.jsf"></p:menuitem>
                <p:menuitem value="Ovos" url="telaOvos.jsf"></p:menuitem>
                <p:menuitem value="Granja Postura" url="telaGranjaOvos.jsf"></p:menuitem>
                <p:menuitem value="Granja Corte" url="telaGranjaCorte.jsf"></p:menuitem>
                <p:menuitem value="Incubátorio" url="telaIncubatorio.jsf"></p:menuitem>
                <p:menuitem value="Vacinas" url="telaVacinas.jsf"></p:menuitem>
                <p:menuitem value="Rações" url="telaRacoes.jsf"></p:menuitem>
                <p:menuitem value="Financeiro" url="telaFinanceiro.jsf"></p:menuitem>
                <p:menuitem value="Relatorios" url="telaRelatorios.jsf"></p:menuitem>
            </p:menubar>
        </h:form>

        <ui:insert></ui:insert>
    </h:body>
</html>

TCC-WEB/web/resources/avecomp/toolbarCrud.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="crudBean" required="true" shortDescription="Uma classe qualquer que extenda o crud"></cc:attribute>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <p:toolbarGroup>
            <p:commandButton value="Pesquisar" action="#{cc.attrs.crudBean.search()}" rendered="#{cc.attrs.crudBean.busca == true}" update="@form" ></p:commandButton>
            <p:commandButton value="Voltar" action="#{cc.attrs.crudBean.returnPes()}" rendered="#{cc.attrs.crudBean.busca == false}" update="@form"></p:commandButton>
            <p:commandButton value="Novo" action="#{cc.attrs.crudBean.newEnt()}" rendered="#{cc.attrs.crudBean.busca == true}" update="@form" ></p:commandButton>
            <p:commandButton value="Salvar" action="#{cc.attrs.crudBean.save()}" rendered="#{cc.attrs.crudBean.busca == false}" update="@form" ></p:commandButton>
            <p:commandButton value="Limpar" action="#{cc.attrs.crudBean.clear()}" rendered="#{cc.attrs.crudBean.busca == true}" update="@form"></p:commandButton>
        </p:toolbarGroup>  
    </cc:implementation>
</html>

TCC-WEB/web/telaFinanceiro.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:decorate xmlns="http://www.w3.org/1999/xhtml"
             xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
             template="menu.xhtml"
             xmlns:h="http://xmlns.jcp.org/jsf/html"
             xmlns:p="http://primefaces.org/ui"
             xmlns:ave="http://xmlns.jcp.org/jsf/composite/avecomp"
             xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Financeiro</title>
    </h:head>
    <h:form>
        <p:messages autoUpdate="true" showDetail="true"></p:messages>
        <p:fieldset>
            <p:panelGrid columns="4">
                <h:outputLabel value="Nome do item:"></h:outputLabel>
                <p:inputText value="#{financeiroBean.entidade.nome}"></p:inputText>
                <h:outputLabel value="Valor:"></h:outputLabel>
                <p:inputText value="#{financeiroBean.entidade.valor}"></p:inputText>
                <h:outputLabel value="Detalhe:"></h:outputLabel>
                <p:inputText value="#{financeiroBean.entidade.detalhe}"></p:inputText>
                <h:outputLabel value="Tipo de transação"></h:outputLabel>
                <p:selectOneMenu value="#{financeiroBean.entidade.entrasaida}">
                    <f:selectItem itemLabel="Selecione..." itemValue="" />
                    <f:selectItem itemLabel="Entrada" itemValue="Entrada" />
                    <f:selectItem itemLabel="Saida" itemValue="Saida" />
                </p:selectOneMenu>
            </p:panelGrid>
            <ave:toolbarCrud crudBean="#{financeiroBean}"></ave:toolbarCrud>
            <br/>
            <br/>
            <p:dataTable value="#{financeiroBean.entidades}" var="f">
                <p:column headerText="Nome do item">
                    <h:outputText value="#{f.nome}"></h:outputText>
                </p:column>
                <p:column headerText="Detalhe">
                    <h:outputText value="#{f.detalhe}"></h:outputText>
                </p:column>
                <p:column headerText="Valor">
                    <h:outputText value="#{f.valor}"></h:outputText>
                </p:column>
                <p:column headerText="Tipo de transição">
                    <h:outputText value="#{f.entrasaida}"></h:outputText>
                </p:column>
                <p:column headerText="Editar">
                    <p:commandButton value="Editar" action="#{financeiroBean.change(f)}" update="@form" ></p:commandButton>
                </p:column>
                <p:column headerText="Excluir">
                    <p:commandButton value="Excluir" action="#{financeiroBean.delete(f)}" update="@form" ></p:commandButton>
                </p:column>
            </p:dataTable>
        </p:fieldset> 
    </h:form>
</ui:decorate>

TCC-WEB/web/telaGranjaCorte.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:decorate xmlns="http://www.w3.org/1999/xhtml"
             xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
             template="menu.xhtml"
             xmlns:ave="http://xmlns.jcp.org/jsf/composite/avecomp"
             xmlns:h="http://xmlns.jcp.org/jsf/html"
             xmlns:p="http://primefaces.org/ui"
             xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Granja de Corte</title>
    </h:head>
    <h:form>
        <p:messages autoUpdate="true" showDetail="true"></p:messages>
        <p:fieldset>
            <p:panelGrid columns="4">
                <h:outputLabel value="Quantidade de aves:"></h:outputLabel>
                <p:inputText value="#{granjaCorteBean.entidade.quantidadeaves}"></p:inputText>
                <h:outputLabel value="Comentário:"></h:outputLabel>
                <p:inputText value="#{granjaCorteBean.entidade.comentario}"></p:inputText>
                <h:outputLabel value="Maximo de aves:"></h:outputLabel>
                <p:inputText value="#{granjaCorteBean.entidade.maximoaves}"></p:inputText>
                <h:outputLabel value="Data de entrada:"></h:outputLabel>
                <p:calendar value="#{granjaCorteBean.entidade.dataentrada}"></p:calendar>
                <h:outputLabel value="Data saida:"></h:outputLabel>
                <p:calendar value="#{granjaCorteBean.entidade.datasaida}"></p:calendar>
                <h:outputLabel value="Mortalidade"></h:outputLabel>
                <p:inputText value="#{granjaCorteBean.entidade.mortalidade}"></p:inputText>
                <h:outputLabel value="Tipo de ave:"></h:outputLabel>
                <p:selectOneMenu value="#{granjaCorteBean.entidade.tipoAve}">
                    <f:selectItem itemLabel="Selecione..." itemValue="" />
                    <f:selectItems value="#{tipoAvesDAO.buscarLista()}" />
                </p:selectOneMenu>
            </p:panelGrid>
            <ave:toolbarCrud crudBean="#{granjaCorteBean}"></ave:toolbarCrud>
            <br/>
            <br/>
            <p:dataTable value="#{granjaCorteBean.entidades}" var="gc">
                <p:column headerText="ID Granja">
                    <h:outputText value="#{gc.id}"></h:outputText>
                </p:column>
                <p:column headerText="Tipo de Ave">
                    <h:outputText value="#{gc.tipoAve}"></h:outputText>
                </p:column>
                <p:column headerText="Mortalidade">
                    <h:outputText value="#{gc.mortalidade}"></h:outputText>
                </p:column>
                <p:column headerText="Quantidade de Aves">
                    <h:outputText value="#{gc.quantidadeaves}"></h:outputText>
                </p:column>
                <p:column headerText="Maximo de aves">
                    <h:outputText value="#{gc.maximoaves}"></h:outputText>
                </p:column>
                <p:column headerText="Data entrada">
                    <p:calendar value="#{gc.dataentrada}" disabled="true"></p:calendar>
                </p:column>
                <p:column headerText="Data saida">
                    <p:calendar value="#{gc.datasaida}" disabled="true"></p:calendar>
                </p:column>
                <p:column headerText="Editar">
                    <p:commandButton value="Editar" action="#{granjaCorteBean.change(gc)}" update="@form" ></p:commandButton>
                </p:column>
                <p:column headerText="Excluir">
                    <p:commandButton value="Excluir" action="#{granjaCorteBean.delete(gc)}" update="@form" ></p:commandButton>
                </p:column>
            </p:dataTable>
        </p:fieldset>
    </h:form>
</ui:decorate>

TCC-WEB/web/telaOvos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:decorate xmlns="http://www.w3.org/1999/xhtml"
             xmlns:h="http://xmlns.jcp.org/jsf/html"
             xmlns:p="http://primefaces.org/ui"
             xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
             template="menu.xhtml"
             xmlns:f="http://xmlns.jcp.org/jsf/core"
             xmlns:ave="http://xmlns.jcp.org/jsf/composite/avecomp">
    <h:head>
        <title>Lotes de ovos</title>
    </h:head>
    <h:form>
        <p:messages autoUpdate="true" showDetail="true"></p:messages>
        <p:fieldset>
            <p:panelGrid columns="4">
                <h:outputLabel value="Lote"></h:outputLabel>
                <p:inputText value="#{ovosBean.entidade.lote}"></p:inputText>
                <h:outputLabel value="Quantidade"></h:outputLabel>
                <p:inputText value="#{ovosBean.entidade.quantidade_ovos}"></p:inputText>
                <h:outputLabel value="Qualidade"></h:outputLabel>
                <p:inputText value="#{ovosBean.entidade.qualidade_ovos}"></p:inputText>
                <h:outputLabel value="Tipo de ave:"></h:outputLabel>
                <p:selectOneMenu value="#{ovosBean.entidade.tipoAve}">
                    <f:selectItem itemLabel="Selecione..." itemValue="" />
                    <f:selectItems value="#{tipoAvesDAO.buscarLista()}" />
                </p:selectOneMenu>
                <h:outputLabel value="Data ponhagem"></h:outputLabel>
                <p:calendar value="#{ovosBean.entidade.data_ponhagem_ovos}"></p:calendar>
                <h:outputLabel value="Incubação"></h:outputLabel>
                <p:selectBooleanCheckbox value="#{ovosBean.entidade.incubacao_ovos}"></p:selectBooleanCheckbox>
                <h:outputLabel value="Todos incubação"></h:outputLabel>
            </p:panelGrid>
            <ave:toolbarCrud crudBean="#{ovosBean}"></ave:toolbarCrud>
            <br/>
            <br/>
            <p:dataTable value="#{ovosBean.entidades}" var="o" rendered="#{ovosBean.busca == true}">
                <p:column headerText="Lote" sortBy="#{o.lote}">
                    <h:outputText value="#{o.lote}"></h:outputText>
                </p:column>
                <p:column headerText="Quantidade">
                    <h:outputText value="#{o.quantidade_ovos}"></h:outputText>
                </p:column>
                <p:column headerText="Qualidade">
                    <h:outputText value="#{o.qualidade_ovos}"></h:outputText>
                </p:column>
                <p:column headerText="Ave">
                    <h:outputText value="#{o.tipoAve}"></h:outputText>
                </p:column>
                <p:column headerText="Data de ponhagem">
                    <p:calendar value="#{o.data_ponhagem_ovos}" disabled="true"></p:calendar>
                </p:column>
                <p:column headerText="Incubação">
                    <p:selectBooleanCheckbox value="#{o.incubacao_ovos}" disabled="true"></p:selectBooleanCheckbox>
                </p:column>
                <p:column headerText="Editar">
                    <p:commandButton value="Editar" action="#{ovosBean.change(o)}" update="@form" ></p:commandButton>
                </p:column>
                <p:column headerText="Excluir">
                     <p:commandButton value="Excluir" action="#{ovosBean.delete(o)}" update="@form" ></p:commandButton>
                </p:column>
            </p:dataTable>
        </p:fieldset>
    </h:form>
</ui:decorate>

TCC-WEB/web/telaRacoes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:decorate xmlns="http://www.w3.org/1999/xhtml"
             xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
             template="menu.xhtml"
             xmlns:ave="http://xmlns.jcp.org/jsf/composite/avecomp"
             xmlns:h="http://xmlns.jcp.org/jsf/html"
             xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Lotes de rações</title>
    </h:head>
    <h:form>
        <p:messages autoUpdate="true" showDetail="true"></p:messages>
        <p:fieldset>
               <p:panelGrid columns="4">
                <h:outputLabel value="Quantidade:"></h:outputLabel>
                <p:inputText value="#{racaoBean.entidade.quantidade}"></p:inputText>
                <h:outputLabel value="Data inicio:"></h:outputLabel>
                <p:calendar value="#{racaoBean.entidade.datainicio}"></p:calendar>
                <h:outputLabel value="Data fim:"></h:outputLabel>
                <p:calendar value="#{racaoBean.entidade.datafim}"></p:calendar>
            </p:panelGrid>
            <ave:toolbarCrud crudBean="#{racaoBean}"></ave:toolbarCrud>
            <br/>
            <br/>
            <p:dataTable value="#{racaoBean.entidades}" var="r" >
                <p:column headerText="Tipo de ração">
                    <h:outputText value="#{r.tiporacao}"></h:outputText>
                </p:column>
                <p:column headerText="Quantidade">
                    <h:outputText value="#{r.quantidade}"></h:outputText>
                </p:column>
                <p:column headerText="Data inicio">
                    <p:calendar value="#{r.datainicio}" disabled="true"></p:calendar>
                </p:column>
                <p:column headerText="Data fim">
                    <p:calendar value="#{r.datafim}" disabled="true"></p:calendar>
                </p:column>
                <p:column headerText="Editar">
                    <p:commandButton value="Editar" action="#{racaoBean.change(r)}" update="@form" ></p:commandButton>
                </p:column>
                <p:column headerText="Excluir">
                    <p:commandButton value="Excluir" action="#{racaoBean.delete(r)}" update="@form" ></p:commandButton>
                </p:column>
            </p:dataTable>
        </p:fieldset>
    </h:form>
</ui:decorate>